[package]
name = "bootstrap"
version = "0.1.0"
edition = "2018"

[build-dependencies]
lalrpop = "0.19.8"

[dependencies]
clap = "2.33.3"
indexmap = "1.9.1"
lalrpop-util = "0.19.8"
llvm-sys = "130"
regex = "1"
